name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
          ### WAIT! PLEASE MAKE SURE THAT YOUR ISSUE HASN'T ALREADY BEEN REPORTED. WE WILL CLOSE ANY DUPLICATE ISSUES.
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please be sure to fill this form out **completely** and follow the format,
        otherwise your issue may get closed without any further clarification.
  - type: markdown
    attributes:
      value: |
        *Please note that we may not acknowledge all issues. If your issue is urgent and has not been acknowledged, please join [our Discord](https://discord.gg/3MPGTCPAEe)!*
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Explain what happened, and steps you took to reproduce this issue.
      value: "X happened..."
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Google Chrome (or Brave, Opera, Microsoft Edge..)
        - Firefox
        - Safari
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
